### ISSUE TITLE
remove digest arg in clientside wasmatic comments

### ISSUE THREAD

**Issue by dakom** [Lay3rLabs/avs-toolkit#84]
currently, the client uploads both the wasm and a sha256 hash of the contents

I'm not sure what it's used for, but the client can easily just lie about the hash - so for the backend to trust it, it would need to recalculate the hash and confirm... so since the backend has it anyway, there doesn't seem to be any benefit at all for the client to supply it

(note- the tooling itself does calculate it, rather than take it as an argument, but a user can still circumvent that and use their own tooling to upload bogus hashes)

**Comment by calvinrp** [comment]
Currently, Wasmatic server-side always computes the digest from the binary itself. The Wasm binaries are also indexed and referenced by their digest on the server.

There are 2 ways to get a Wasm binary to Wasmatic (on the current release).
1. `POST /app` with `wasmUrl` and `digest`
In this case, Wasmatic downloads the file from that URL and verifies the `digest` matches the expected.
This is important to verify that the binary is the expected binary provided by a potentially 3rd party URL source as well as doing an integrity check that it was downloaded correctly.

2. `POST /upload` and then followed by `POST /app` with `digest`
The `/upload` endpoint stores the Wasm binary and indexes it by its server-side computed digest.
Next, you refer to the Wasm file by the `digest` in the `POST /app` request to registry the app so that Wasmatic knows which Wasm file it should use.

In both cases, the `digest` is important for the client to provide.
